### ISSUE TITLE
sqlite file

### ISSUE THREAD

**Issue by AndreasReitberger** [ohtejera/leaderboardC2#2]
Hi,
I tried to rename the test.sqlite file, but there are still some scores included.
How do I create an empty one?

Thank you!

**Comment by ohtejera** [comment]
Hi Andreas, 

I just adding a new empty SQLite database [here](https://github.com/ohtejera/leaderboardC2/tree/master/data) and also a SQL dump file.

Please remember that you need ensure that the permissions for the data folder and your **base.sqlite** file are set to **0777** and also that the **.sqlite** file name should be equal to the **Game ID** property on the LeaderboardC2 Construct2 plugin. 

Please let me know if you have any questions.
Best regards,
Henry

**Comment by AndreasReitberger** [comment]
Awesome :) thank you very much Henry!
Kind regards 
Andreas

**Comment by ohtejera** [comment]
You're welcome!
